export const KanaData = {
    // Hiragana
    'あ': { kana: 'あ', eng: "a" },
    'い': { kana: 'い', eng: "i" },
    'う': { kana: 'う', eng: "u" },
    'え': { kana: 'え', eng: "e" },
    'お': { kana: 'お', eng: "o" },
    'か': { kana: 'か', eng: "ka" },
    'き': { kana: 'き', eng: "ki" },
    'く': { kana: 'く', eng: "ku" },
    'け': { kana: 'け', eng: "ke" },
    'こ': { kana: 'こ', eng: "ko" },
    'さ': { kana: 'さ', eng: "sa" },
    'し': { kana: 'し', eng: "shi" },
    'す': { kana: 'す', eng: "su" },
    'せ': { kana: 'せ', eng: "se" },
    'そ': { kana: 'そ', eng: "so" },
    'た': { kana: 'た', eng: "ta" },
    'ち': { kana: 'ち', eng: "chi" },
    'つ': { kana: 'つ', eng: "tsu" },
    'て': { kana: 'て', eng: "te" },
    'と': { kana: 'と', eng: "to" },
    'な': { kana: 'な', eng: "na" },
    'に': { kana: 'に', eng: "ni" },
    'ぬ': { kana: 'ぬ', eng: "nu" },
    'ね': { kana: 'ね', eng: "ne" },
    'の': { kana: 'の', eng: "no" },
    'は': { kana: 'は', eng: "ha" },
    'ひ': { kana: 'ひ', eng: "hi" },
    'ふ': { kana: 'ふ', eng: "fu" },
    'へ': { kana: 'へ', eng: "he" },
    'ほ': { kana: 'ほ', eng: "ho" },
    'ま': { kana: 'ま', eng: "ma" },
    'み': { kana: 'み', eng: "mi" },
    'む': { kana: 'む', eng: "mu" },
    'め': { kana: 'め', eng: "me" },
    'も': { kana: 'も', eng: "mo" },
    'や': { kana: 'や', eng: "ya" },
    'ゆ': { kana: 'ゆ', eng: "yu" },
    'よ': { kana: 'よ', eng: "yo" },
    'ら': { kana: 'ら', eng: "ra" },
    'り': { kana: 'り', eng: "ri" },
    'る': { kana: 'る', eng: "ru" },
    'れ': { kana: 'れ', eng: "re" },
    'ろ': { kana: 'ろ', eng: "ro" },
    'わ': { kana: 'わ', eng: "wa" },
    'を': { kana: 'を', eng: "wo" },
    'ん': { kana: 'ん', eng: "n" },
    'きゃ': { kana: 'きゃ', eng: 'kya' },
    'きゅ': { kana: 'きゅ', eng: 'kyu' },
    'きょ': { kana: 'きょ', eng: 'kyo' },
    'ぎゃ': { kana: 'ぎゃ', eng: 'gya' },
    'ぎゅ': { kana: 'ぎゅ', eng: 'gyu' },
    'ぎょ': { kana: 'ぎょ', eng: 'gyo' },
    'しゃ': { kana: 'しゃ', eng: 'sha' },
    'しゅ': { kana: 'しゅ', eng: 'shu' },
    'しょ': { kana: 'しょ', eng: 'sho' },
    'じゃ': { kana: 'じゃ', eng: 'ja' },
    'じゅ': { kana: 'じゅ', eng: 'ju' },
    'じょ': { kana: 'じょ', eng: 'jo' },
    'ちゃ': { kana: 'ちゃ', eng: 'cha' },
    'ちゅ': { kana: 'ちゅ', eng: 'chu' },
    'ちょ': { kana: 'ちょ', eng: 'cho' },
    'にゃ': { kana: 'にゃ', eng: 'nya' },
    'にゅ': { kana: 'にゅ', eng: 'nyu' },
    'にょ': { kana: 'にょ', eng: 'nyo' },
    'ひゃ': { kana: 'ひゃ', eng: 'hya' },
    'ひゅ': { kana: 'ひゅ', eng: 'hyu' },
    'ひょ': { kana: 'ひょ', eng: 'hyo' },
    'びゃ': { kana: 'びゃ', eng: 'bya' },
    'びゅ': { kana: 'びゅ', eng: 'byu' },
    'びょ': { kana: 'びょ', eng: 'byo' },
    'ぴゃ': { kana: 'ぴゃ', eng: 'pya' },
    'ぴゅ': { kana: 'ぴゅ', eng: 'pyu' },
    'ぴょ': { kana: 'ぴょ', eng: 'pyo' },
    'みゃ': { kana: 'みゃ', eng: 'mya' },
    'みゅ': { kana: 'みゅ', eng: 'myu' },
    'みょ': { kana: 'みょ', eng: 'myo' },
    'りゃ': { kana: 'りゃ', eng: 'rya' },
    'りゅ': { kana: 'りゅ', eng: 'ryu' },
    'りょ': { kana: 'りょ', eng: 'ryo' },
    // Katakana
    'ア': { kana: 'ア', eng: 'a' },
    'イ': { kana: 'イ', eng: 'i' },
    'ウ': { kana: 'ウ', eng: 'u' },
    'エ': { kana: 'エ', eng: 'e' },
    'オ': { kana: 'オ', eng: 'o' },
    'カ': { kana: 'カ', eng: 'ka' },
    'キ': { kana: 'キ', eng: 'ki' },
    'ク': { kana: 'ク', eng: 'ku' },
    'ケ': { kana: 'ケ', eng: 'ke' },
    'コ': { kana: 'コ', eng: 'ko' },
    'ガ': { kana: 'ガ', eng: 'ga' },
    'ギ': { kana: 'ギ', eng: 'gi' },
    'グ': { kana: 'グ', eng: 'gu' },
    'ゲ': { kana: 'ゲ', eng: 'ge' },
    'ゴ': { kana: 'ゴ', eng: 'go' },
    'サ': { kana: 'サ', eng: 'sa' },
    'シ': { kana: 'シ', eng: 'shi' },
    'ス': { kana: 'ス', eng: 'su' },
    'セ': { kana: 'セ', eng: 'se' },
    'ソ': { kana: 'ソ', eng: 'so' },
    'ザ': { kana: 'ザ', eng: 'za' },
    'ジ': { kana: 'ジ', eng: 'ji' },
    'ズ': { kana: 'ズ', eng: 'zu' },
    'ゼ': { kana: 'ゼ', eng: 'ze' },
    'ゾ': { kana: 'ゾ', eng: 'zo' },
    'タ': { kana: 'タ', eng: 'ta' },
    'チ': { kana: 'チ', eng: 'chi' },
    'ツ': { kana: 'ツ', eng: 'tsu' },
    'テ': { kana: 'テ', eng: 'te' },
    'ト': { kana: 'ト', eng: 'to' },
    'ダ': { kana: 'ダ', eng: 'da' },
    'ヂ': { kana: 'ヂ', eng: 'ji' },
    'ヅ': { kana: 'ヅ', eng: 'zu' },
    'デ': { kana: 'デ', eng: 'de' },
    'ド': { kana: 'ド', eng: 'do' },
    'ナ': { kana: 'ナ', eng: 'na' },
    'ニ': { kana: 'ニ', eng: 'ni' },
    'ヌ': { kana: 'ヌ', eng: 'nu' },
    'ネ': { kana: 'ネ', eng: 'ne' },
    'ノ': { kana: 'ノ', eng: 'no' },
    'ハ': { kana: 'ハ', eng: 'ha' },
    'ヒ': { kana: 'ヒ', eng: 'hi' },
    'フ': { kana: 'フ', eng: 'fu' },
    'ヘ': { kana: 'ヘ', eng: 'he' },
    'ホ': { kana: 'ホ', eng: 'ho' },
    'バ': { kana: 'バ', eng: 'ba' },
    'ビ': { kana: 'ビ', eng: 'bi' },
    'ブ': { kana: 'ブ', eng: 'bu' },
    'ベ': { kana: 'ベ', eng: 'be' },
    'ボ': { kana: 'ボ', eng: 'bo' },
    'パ': { kana: 'パ', eng: 'pa' },
    'ピ': { kana: 'ピ', eng: 'pi' },
    'プ': { kana: 'プ', eng: 'pu' },
    'ペ': { kana: 'ペ', eng: 'pe' },
    'ポ': { kana: 'ポ', eng: 'po' },
    'マ': { kana: 'マ', eng: 'ma' },
    'ミ': { kana: 'ミ', eng: 'mi' },
    'ム': { kana: 'ム', eng: 'mu' },
    'メ': { kana: 'メ', eng: 'me' },
    'モ': { kana: 'モ', eng: 'mo' },
    'ヤ': { kana: 'ヤ', eng: 'ya' },
    'ユ': { kana: 'ユ', eng: 'yu' },
    'ヨ': { kana: 'ヨ', eng: 'yo' },
    'ラ': { kana: 'ラ', eng: 'ra' },
    'リ': { kana: 'リ', eng: 'ri' },
    'ル': { kana: 'ル', eng: 'ru' },
    'レ': { kana: 'レ', eng: 're' },
    'ロ': { kana: 'ロ', eng: 'ro' },
    'ワ': { kana: 'ワ', eng: 'wa' },
    'ヲ': { kana: 'ヲ', eng: 'wo' },
    'ン': { kana: 'ン', eng: 'n' },
    'キャ': { kana: 'キャ', eng: 'kya' },
    'キュ': { kana: 'キュ', eng: 'kyu' },
    'キョ': { kana: 'キョ', eng: 'kyo' },
    'ギャ': { kana: 'ギャ', eng: 'gya' },
    'ギュ': { kana: 'ギュ', eng: 'gyu' },
    'ギョ': { kana: 'ギョ', eng: 'gyo' },
    'シャ': { kana: 'シャ', eng: 'sha' },
    'シュ': { kana: 'シュ', eng: 'shu' },
    'ショ': { kana: 'ショ', eng: 'sho' },
    'ジャ': { kana: 'ジャ', eng: 'ja' },
    'ジュ': { kana: 'ジュ', eng: 'ju' },
    'ジョ': { kana: 'ジョ', eng: 'jo' },
    'チャ': { kana: 'チャ', eng: 'cha' },
    'チュ': { kana: 'チュ', eng: 'chu' },
    'チョ': { kana: 'チョ', eng: 'cho' },
    'ニャ': { kana: 'ニャ', eng: 'nya' },
    'ニュ': { kana: 'ニュ', eng: 'nyu' },
    'ニョ': { kana: 'ニョ', eng: 'nyo' },
    'ヒャ': { kana: 'ヒャ', eng: 'hya' },
    'ヒュ': { kana: 'ヒュ', eng: 'hyu' },
    'ヒョ': { kana: 'ヒョ', eng: 'hyo' },
    'ビャ': { kana: 'ビャ', eng: 'bya' },
    'ビュ': { kana: 'ビュ', eng: 'byu' },
    'ビョ': { kana: 'ビョ', eng: 'byo' },
    'ピャ': { kana: 'ピャ', eng: 'pya' },
    'ピュ': { kana: 'ピュ', eng: 'pyu' },
    'ピョ': { kana: 'ピョ', eng: 'pyo' },
    'ミャ': { kana: 'ミャ', eng: 'mya' },
    'ミュ': { kana: 'ミュ', eng: 'myu' },
    'ミョ': { kana: 'ミョ', eng: 'myo' },
    'リャ': { kana: 'リャ', eng: 'rya' },
    'リュ': { kana: 'リュ', eng: 'ryu' },
    'リョ': { kana: 'リョ', eng: 'ryo' },
};

export const KanaGridTypes = Object.freeze({
    Hiragana: 1,
    Katakana: 2,
});

export const HiraganaGridLayout = [
    ['あ', 'い', 'う', 'え', 'お'],
    ['か', 'き', 'く', 'け', 'こ'],
    ['さ', 'し', 'す', 'せ', 'そ'],
    ['た', 'ち', 'つ', 'て', 'と'],
    ['な', 'に', 'ぬ', 'ね', 'の'],
    ['は', 'ひ', 'ふ', 'へ', 'ほ'],
    ['ま', 'み', 'む', 'め', 'も'],
    ['や', '', 'ゆ', '', 'よ'],
    ['ら', 'り', 'る', 'れ', 'ろ'],
    ['わ', '', '', '', 'を'],
    ['ん', '', '', '', '']
];

export const KatakanaGridLayout = [
    ['ア', 'イ', 'ウ', 'エ', 'オ'],
    ['カ', 'キ', 'ク', 'ケ', 'コ'],
    ['サ', 'シ', 'ス', 'セ', 'ソ'],
    ['タ', 'チ', 'ツ', 'テ', 'ト'],
    ['ナ', 'ニ', 'ヌ', 'ネ', 'ノ'],
    ['ハ', 'ヒ', 'フ', 'ヘ', 'ホ'],
    ['マ', 'ミ', 'ム', 'メ', 'モ'],
    ['ヤ', '', 'ユ', '', 'ヨ'],
    ['ラ', 'リ', 'ル', 'レ', 'ロ'],
    ['ワ', '', '', '', 'ヲ'],
    ['ン', '', '', '', '']
];

export const KanaGojuon = ['あ', 'い', 'う', 'え', 'お', 'か', 'き', 'く', 'け', 'こ', 'さ', 'し', 'す', 'せ', 'そ', 'た', 'ち', 'つ', 'て', 'と', 'な', 'に', 'ぬ', 'ね', 'の', 'は', 'ひ', 'ふ', 'へ', 'ほ', 'ま', 'み', 'む', 'め', 'も', 'や', 'ゆ', 'よ', 'ら', 'り', 'る', 'れ', 'ろ', 'わ', 'を', 'ん'];
